name: Update Playwright Snapshots

on:
  workflow_dispatch:
    inputs:
      updateSnapshots:
        description: "Update Playwright snapshots"
        required: false
        type: boolean

jobs:
  update_snapshots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t wcc-playwright .

      - name: Update Playwright snapshots
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/playwright-report:/app/playwright-report \
            -v ${{ github.workspace }}/playwright-tests/screenshots:/app/playwright-tests/screenshots \
            wcc-playwright sh -c "pnpm test:e2e --update-snapshots"

      - name: Commit updated snapshots
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add playwright-tests/screenshots
          git commit -m "chore: update Playwright snapshots"
          git push

      - name: Upload Playwright test reports
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
